version: "3"
services:
  redis:
      image: redis:4.0
      restart: always
      ports:
        - 6379:6379
      command: ['redis-server', '--requirepass', '123456']
      deploy:
        replicas: 1
  
  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
      ports:
      - "8081:8081"